import ArduinoHR from './ArduinoHR';
import BestOnlineGame from './BestOnlineGame';
import CarbonTracker from './CarbonTracker';
import CheapBooze from './CheapBooze';
import DbReaderTurnpike from './DbReaderTurnpike';
import HBIDeployment from './HBIDeployment';
import HackhatonShowcase from './HackhatonShowcase';
import HostDataGen from './HostDataGen';
import InsightsGivesBack from './InsightsGivesBack';
import MacroArduinoKB from './MacroArduinoKB';
import MarioGame from './MarioGame';
import NotAStarWarsGame from './NotAStarWarsGame';
import Pluggy from './Pluggy';
import RhDataScience from './RhDataScience';
import SpotifyCli from './SpotifyCli';
import StorWars from './StorWars';
import StreamDeck from './StreamDeck';
import UnityPuzzle from './UnityPuzzle';
export default [ArduinoHR,BestOnlineGame,CarbonTracker,CheapBooze,DbReaderTurnpike,HBIDeployment,HackhatonShowcase,HostDataGen,InsightsGivesBack,MacroArduinoKB,MarioGame,NotAStarWarsGame,Pluggy,RhDataScience,SpotifyCli,StorWars,StreamDeck,UnityPuzzle]